#!/usr/bin/bash

export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# set text color constants
RED="\e[91m"
GREEN="\e[92m"
YELLOW="\e[93m"
MAGENTA="\e[95m"
BOLDYELLOW="\e[1;${YELLOW}"
BOLDGREEN="\e[1;${GREEN}"
BOLDRED="\e[1;${RED}"
REDBACKGROUND="\e[41m"
GREENBACKGROUND="\e[42m"
YELLOWBACKGROUND="\e[43m"
ENDCOLOR="\e[0m"

# Set up script error handling see https://disconnected.systems/blog/another-bash-strict-mode for details
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'

echo -e "${REDBACKGROUND}▄▖____▌_▖_▘________▄▖▄▖▖__▖__▄▖___________▄▖______▗_____${ENDCOLOR}"
echo -e "${REDBACKGROUND}▌▌▛▘▛▘▛▌▌_▌▛▌▌▌▚▘▄▖▌▌▙▘▛▖▞▌__▐_▛▛▌▀▌▛▌█▌__▌_▛▘█▌▀▌▜▘▛▌▛▘${ENDCOLOR}"
echo -e "${REDBACKGROUND}▛▌▌_▙▖▌▌▙▖▌▌▌▙▌▞▖__▛▌▌▌▌▝_▌__▟▖▌▌▌█▌▙▌▙▖__▙▖▌_▙▖█▌▐▖▙▌▌_${ENDCOLOR}"
echo -e "${REDBACKGROUND}____________________________________▄▌__________________${ENDCOLOR}"

echo -e "${MAGENTA} ==> Creates an Arch Linux ARM image e.g. for installation to an SD card. ${ENDCOLOR}"

# Ensure we are root
if [[ $EUID -ne 0 ]]; then
  echo -e "${YELLOW} This script must be run as root! ${ENDCOLOR}"
  exit 1
fi

# Some useful constants
mount="mnt" # Local directory to mount the image (automatically created/delete as needed)
base_url="http://archlinuxarm.org/os"

# Grab the first two arguments, using the defaults if not set
# For example, to create a 4 gig image called archlinux-rpi-armv7.img
# that automatically runs ./setup1 and ./setup2 inside the new root, use:
#
#   ./create-image 4G rpi-armv7 ./setup1 ./setup2
#

if [ $# -lt 2 ]; then
echo -e "${YELLOW}Usage: $0 <size> <arch> <setup scripts...>${ENDCOLOR}"
  exit 1
fi

size="$1"
shift

arch="$1"
shift

file="ArchLinuxARM-${arch}-latest.tar.gz"
image="archlinux-${arch}.img"
mirrorscript="fastestmirror.sh"
URL="https://aur.archlinux.org/yay-bin.git"
STAGING_PATH="/usr/src/yay-bin"
locales="en_US.UTF-8"

# Local setup script to run inside the image
script_sources=("$@")
script_destdir="/setup-scripts"
script_destdir2="/etc/init.d"
loopdev=

# Tasks to run when the shell exits for any reason, unmount the image and
# general cleanup
echo -e "${YELLOW}==> Cleanup: Unmount the image and general cleanup.${ENDCOLOR}"
cleanup() {
  rm -rf "${mount}${script_destdir}"
  if [[ -d "${mount}" ]]; then
    umount -R "${mount}" || true
    rmdir "${mount}" || true
  fi
  [ -n "${loopdev}" ] && losetup --detach "${loopdev}" || true
}
trap cleanup EXIT

echo -e "${YELLOW}==> Downloading Arch Linux ARM tarball (${file})...${ENDCOLOR}"
#[ ! -f "${file}" ] && wget --quiet "${base_url}/${file}"
[ ! -f "${file}" ] && curl -LO "${base_url}/${file}"

  echo -e "${BOLDRED}==> Creating image...${ENDCOLOR}"
dd if=/dev/zero of="${image}" bs=1 seek="${size}" count=0
loopdev=$(losetup --find --show "${image}")

echo -e "${YELLOW}==> Partitioning image...${ENDCOLOR}"
parted --script "${loopdev}" mklabel msdos
parted --script "${loopdev}" mkpart primary fat32 0% 200M
parted --script "${loopdev}" mkpart primary ext4 200M 100%

echo -e "${YELLOW}==> Formatting image...${ENDCOLOR}"
bootdev=$(ls "${loopdev}"*1)
rootdev=$(ls "${loopdev}"*2)

# Format with f2fs
#mkfs.vfat -I -n SYSTEM ${bootdev}
#mkfs.f2fs -f -l root ${rootdev}

# Format with ext4
mkfs.vfat -I -n SYSTEM ${bootdev}
mkfs.ext4 -F -L root -b 4096 -E stride=4,stripe_width=1024 ${rootdev}

echo -e "${YELLOW}==> Mounting image...${ENDCOLOR}"
[ ! -d "${mount}" ] && mkdir "${mount}"
mount "${rootdev}" "${mount}"
[ ! -d "${mount}/boot" ] && mkdir "${mount}/boot"
mount "${bootdev}" "${mount}/boot"

echo -e "${BOLDRED}==> Installing Arch Linux ARM root tree to image...${ENDCOLOR}"
  tar -xpf "${file}" -C "${mount}" 2> >(grep -v "Ignoring unknown extended header keyword")

echo -e "${BOLDRED}==> Installing overlay tree to image...${ENDCOLOR}"
  rsync -rlDvP "$(dirname $0)/overlay/" "${mount}/"

echo -e "${BOLDRED}==> Setting up pacman keyring...${ENDCOLOR}"

cat <<EOF | arch-chroot "${mount}"
  pacman-key --init
  pacman-key --populate archlinuxarm
EOF

echo -e "${BOLDRED}==> Setting up setup scripts dir...  ${ENDCOLOR}"
  mkdir "${mount}${script_destdir}"

echo -e "${BOLDYELLOW}==> Run mirrorscript scripts inside new root...  ${ENDCOLOR}"
  script_dest="${script_destdir}/$(basename $mirrorscript)"
  
echo -e "${BOLDRED}==> Installing $mirrorscript to $script_dest in new root...  ${ENDCOLOR}"
  install -Dm755 "$mirrorscript" "${mount}${script_dest}"

echo -e "${BOLDYELLOW}==> Running $script_dest...  ${ENDCOLOR}"
  sudo arch-chroot "${mount}" "${script_dest}"

echo -e "${BOLDRED}==> Setting up Tools and needed Apps...  ${ENDCOLOR}"
echo -e "${YELLOWBACKGROUND} ==> Coffee break!? That might take a while.  ${ENDCOLOR}"

cat <<EOF | arch-chroot "${mount}" 
  pacman -Syu --noconfirm --needed vim git sudo dpkg go python base-devel devtools unzip wget mc gcc cmake f2fs-tools lsb-release fakeroot python-setuptools python-pip python-pipx tk arch-install-scripts
EOF

echo -e "${YELLOWBACKGROUND}==> Configure system locale to en_US.UTF-8...  ${ENDCOLOR}"

# Configure system locale to en_US.UTF-8
  arch-chroot "${mount}" sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/g' /etc/locale.gen
  arch-chroot "${mount}" locale-gen
  arch-chroot "${mount}" echo 'LANG=en_US.UTF-8' > /etc/locale.conf
  arch-chroot "${mount}" echo 'LANG="en_US.UTF-8"' > /etc/environment
  arch-chroot "${mount}" echo 'LC_ALL=“en_US.UTF-8”' > /etc/environment
  
echo -e "${BOLDRED}==> Setting up service for expanding fs on first boot...  ${ENDCOLOR}"
  cat <<EOF | arch-chroot "${mount}"
  systemctl enable expand-rootfs
EOF
  
echo -e "${BOLDRED}==> Setting up the alarm user...  ${ENDCOLOR}"
  groupadd -g 999 sudo && useradd -u 999 -g alarm -G sudo -m -s /bin/bash alarm && \
  sed -i /etc/sudoers -re 's/^%sudo.*/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/g' && \
  sed -i /etc/sudoers -re 's/^root.*/root ALL=(ALL:ALL) NOPASSWD: ALL/g' && \
  sed -i /etc/sudoers -re 's/^#includedir.*/## **Removed the include directive** ##"/g' && \
  echo "alarm ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
  echo "Customized the sudoers file for passwordless access to the alarm user!" && \
  echo "alarm user:";  su - alarm -c id

# Run setup scripts inside new root
for script in "${script_sources[@]}"; do
  script_dest="${script_destdir}/$(basename "$script")"

echo -e "${BOLDRED}==> Installing $script to $script_dest in new root... ${ENDCOLOR}"
  install -Dm755 "$script" "${mount}${script_dest}"
echo -e "${BOLDRED}==> Installing resize2fs to $script_destdir2 in new root... ${ENDCOLOR}"
  install -Dm755 "resize2fs_once" "${mount}${script_destdir2}"
echo -e "${BOLDRED}==> Running $script_dest...${ENDCOLOR}"
  arch-chroot "${mount}" "${script_dest}"
echo -e "${BOLDRED}==> Removing $script_dest from new root... ${ENDCOLOR}"
  rm "${mount}${script_dest}"

done

echo -e "${BOLDRED}==> Cleaning pacman cache...${ENDCOLOR}"
cat <<EOF | arch-chroot "${mount}"
yes | pacman -Scc

EOF

echo -e "${GREENBACKGROUND} ▄▖____________________________▗____▌________________▐▘__▜_▜_____${ENDCOLOR}"
echo -e "${GREENBACKGROUND} ▐_▛▛▌▀▌▛▌█▌__▌▌▌▀▌▛▘__▛▘▛▘█▌▀▌▜▘█▌▛▌__▛▘▌▌▛▘▛▘█▌▛▘▛▘▜▘▌▌▐_▐_▌▌__${ENDCOLOR}"
echo -e "${GREENBACKGROUND} ▟▖▌▌▌█▌▙▌▙▖__▚▚▘█▌▄▌__▙▖▌_▙▖█▌▐▖▙▖▙▌__▄▌▙▌▙▖▙▖▙▖▄▌▄▌▐_▙▌▐▖▐▖▙▌▗_${ENDCOLOR}"
echo -e "${GREENBACKGROUND} _______▄▌___________________________________________________▄▌__${ENDCOLOR}"