#!/bin/bash

export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export LC_CTYPE=en_US.UTF-8

# set text color constants
RED="\e[91m"
GREEN="\e[32m"
YELLOW="\e[33m"
MAGENTA="\e[35m"
BOLDYELLOW="\e[1;${YELLOW}"
BOLDGREEN="\e[1;${GREEN}"
BOLDRED="\e[1;${RED}"
REDBACKGROUND="\e[41m"
GREENBACKGROUND="\e[42m"
YELLOWBACKGROUND="\e[43m"
ENDCOLOR="\e[0m"

set -uo pipefail

URL="https://github.com/Jguer/yay.git"
STAGING_PATH="yay"
locales="en_US.UTF-8"
mount="mnt"

echo "                               ";
echo "▖▖▄▖▖▖  ▄▖    ▗   ▜ ▜   ▗ ▘    ";
echo "▌▌▌▌▌▌  ▐ ▛▌▛▘▜▘▀▌▐ ▐ ▀▌▜▘▌▛▌▛▌";
echo "▐ ▛▌▐   ▟▖▌▌▄▌▐▖█▌▐▖▐▖█▌▐▖▌▙▌▌▌";
echo "                               ";
echo -e "${BOLDRED}==> Installing YAY... ${ENDCOLOR}"
echo -e "${YELLOWBACKGROUND}==> Please wait. It will take a while... ${ENDCOLOR}"

git clone "$URL" "$STAGING_PATH"
cd "$STAGING_PATH" && make install
echo -e "${GREEN}==> YAY installed... ${ENDCOLOR}"

