#!/usr/bin/bash

CFG_FILE=config.conf
CFG_CONTENT=$(cat $CFG_FILE | sed -r '/[^=]+=[^=]+/!d' | sed -r 's/\s+=\s/=/g')
eval "$CFG_CONTENT"

export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export LANG=LANG en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# set text color constants 
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
MAGENTA="\e[35m"
BOLDGREEN="\e[1;${GREEN}m"
BOLDRED="\e[1;${RED}m"
REDBACKGROUND="\e[41m"
GREENBACKGROUND="\e[42m"
YELLOWBACKGROUND="\e[43m"
ENDCOLOR="\e[0m"

set -uo pipefail

URL="https://github.com/Jguer/yay.git"
STAGING_PATH="yay"
locales="en_US.UTF-8"
mount="mnt"

echo -e "${RED}==> Installing YAY... ${ENDCOLOR}"
echo -e "${YELLOWBACKGROUND}==> Please wait. It will take a while... ${ENDCOLOR}"

git clone "$URL" "$STAGING_PATH"
cd "$STAGING_PATH" && make install

