#!/usr/bin/bash
export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export LANG=LANG en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

set -uo pipefail
echo -e "\e[0;32m""==> Installing Kernel and div. Tools"
pacman -R --noconfirm linux-aarch64 uboot-raspberrypi
pacman -Syu --noconfirm --needed linux-rpi raspberrypi-bootloader raspberrypi-utils


